Color Recommendation Portal
thedatatribune/dyPixa pull request #51
Opened 2023-10-05 07:25 UTC by RajaVardhan-coder

## Pull Request for Issue #30

### Description

This pull request addresses issue #30, which involves the development of the [UI/Frontend] Color Recommendation Portal. Here are the key changes included in this PR:

- Created an interactive web portal for users to input text.
- Integrated the Flask backend to handle text input and generate color recommendations.
- Designed a modern and colorful user interface with a gradient background.
- Displayed recommended colors in square boxes below the input field.

2023-10-05 16:53 UTC, harishankar1014 commented on frontend/ColourRecommandation/templates/index.html
> +    <form method="post" action="/recommend">
There is no need for the method="post" and action="/recommend" in the form as you have already used the submit button as an event listener. Just thought that you should change it to make the code cleaner.

2023-10-05 16:56 UTC, harishankar1014 requested changes
In the form element of index.html you are doing an unnecessary post request as the JavaScript call is used to use the button as an event listener. You can remove the unnecessary call from the form to make the code cleaner.

2023-10-06 02:55 UTC, harishankar1014 approved these changes

2023-10-06 02:56 UTC, harishankar1014 approved these changes
The required changes were made (removed unnecessary attributes from form)

2023-10-06 16:12 UTC, ravi-prakash1907 approved these changes

2023-10-06 16:12 UTC, merged